import React, { createContext, useContext, useState, useEffect } from 'react';
import { auth } from '../config/firebase';
import { 
  createUserWithEmailAndPassword, 
  signInWithEmailAndPassword, 
  signOut, 
  onAuthStateChanged,
  signInWithCustomToken,
  type User as FirebaseUser
} from 'firebase/auth';
import api from '../services/api';

export interface User {
  id: string;
  email: string;
  name: string;
  phone: string;
  role: 'VICTIM' | 'VOLUNTEER' | 'RESCUE' | 'ADMIN';
  volunteer?: {
    id: string;
    status: string;
    skills: string;
  };
}

interface AuthContextType {
  user: User | null;
  token: string | null;
  loading: boolean;
  login: (email: string, password: string) => Promise<User>;
  register: (data: any) => Promise<User>;
  logout: () => Promise<void>;
  updateCachedUser: (user: User) => void;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser: FirebaseUser | null) => {
      if (firebaseUser) {
        try {
          const idToken = await firebaseUser.getIdToken();
          setToken(idToken);
          localStorage.setItem('signalflare_token', idToken);
          
          // Fetch user data from backend (bypasses Firestore client rules)
          const response = await api.get('/auth/me');
          const userData = response.data as User;
          
          setUser(userData);
          localStorage.setItem('signalflare_user', JSON.stringify(userData));
        } catch (error) {
          console.error("Error fetching user data from backend:", error);
        }
      } else {
        setToken(null);
        setUser(null);
        localStorage.removeItem('signalflare_token');
        localStorage.removeItem('signalflare_user');
      }
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const login = async (email: string, password: string) => {
    try {
      const userCredential = await signInWithEmailAndPassword(auth, email, password);
      const idToken = await userCredential.user.getIdToken();
      localStorage.setItem('signalflare_token', idToken);

      const response = await api.get('/auth/me');
      const userData = response.data as User;
      
      setUser(userData);
      return userData;
    } catch (err: any) {
      // Offline fallback check: if offline, check if matches cached user email
      const cachedUserJson = localStorage.getItem('signalflare_user');
      if (!navigator.onLine && cachedUserJson) {
        const cachedUser = JSON.parse(cachedUserJson) as User;
        if (cachedUser.email === email) {
          setUser(cachedUser);
          setToken('offline_token');
          return cachedUser;
        }
      }
      throw err;
    }
  };

  const register = async (data: any) => {
    // We call the backend to register to bypass Firestore client security rules
    const response = await api.post('/auth/register', data);
    const { token: customToken, user: newUser } = response.data;
    
    // Sign in with the custom token generated by the backend Admin SDK
    await signInWithCustomToken(auth, customToken);

    setUser(newUser);
    return newUser;
  };

  const logout = async () => {
    try {
      await signOut(auth);
    } catch (err) {
      console.error('Logout warning:', err);
    } finally {
      localStorage.removeItem('signalflare_token');
      localStorage.removeItem('signalflare_user');
      setToken(null);
      setUser(null);
    }
  };

  const updateCachedUser = (updatedUser: User) => {
    setUser(updatedUser);
    localStorage.setItem('signalflare_user', JSON.stringify(updatedUser));
  };

  return (
    <AuthContext.Provider
      value={{ user, token, loading, login, register, logout, updateCachedUser }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};
